### ISSUE TITLE
Uncaught abort()

### ISSUE THREAD

**Issue by bhaskar-c** [higuma/ogg-vorbis-encoder-js#6]
I am getting the following error:

> Uncaught abort() at Error
>     at jsStackTrace (http://localhost:5003/js/utils/OggVorbisEncoder.js:1154:13)
>     at stackTrace (http://localhost:5003/js/utils/OggVorbisEncoder.js:1171:22)
>     at Object.abort (http://localhost:5003/js/utils/OggVorbisEncoder.js:37223:44)
>     at _abort (http://localhost:5003/js/utils/OggVorbisEncoder.js:1795:22)
>     at _free (http://localhost:5003/js/utils/OggVorbisEncoder.js:32741:3)
>     at _encoder_clear (http://localhost:5003/js/utils/OggVorbisEncoder.js:29281:2)
>     at Encoder.cancel.Encoder.cleanup (http://localhost:5003/js/utils/OggVorbisEncoder.js:37294:5)
>     at Encoder.finish (http://localhost:5003/js/utils/OggVorbisEncoder.js:37289:10)
>     at encode (http://localhost:5003/js/utils/worker.js:13:21)
>     at self.onmessage (http://localhost:5003/js/utils/worker.js:19:9)
> If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

Here's my worker.js code:

```
(function () {
  'use strict';
  self.OggVorbisEncoderConfig = {  
	  memoryInitializerPrefixURL: "./" ,
	  TOTAL_MEMORY: 536870912
	  };
  importScripts('./OggVorbisEncoder.js');

var encode = function (samplesLeft, samplesRight) {
	var buffers = [samplesLeft, samplesRight]
	var encoder = new OggVorbisEncoder(44100, 2, 1)
	encoder.encode(buffers)
	var blob = encoder.finish()
    self.postMessage({cmd: 'end', blob: blob });
  };

  self.onmessage = function (e) {
    if(e.data.cmd == 'encode') {
        encode(e.data.samplesLeft, e.data.samplesRight);
        
    }
  };

})();

```
If i remove the memory line from the above worker.js code, I get the following error:

> Uncaught RangeError: Source is too large
>     at Float32Array.set (native)
>     at Encoder.encode (http://localhost:5003/js/utils/OggVorbisEncoder.min.js:13:30511)
>     at encode

I am trying this with a 4.03 minutes worth of samples at 44100 sample rate.

Thanks a lot

**Comment by Adavo** [comment]
Similar issue here:

```
pre-main prep time: 48 ms
OggVorbisEncoder.min.js:1 3
OggVorbisEncoder.min.js:1 3
OggVorbisEncoder.min.js:13 Uncaught abort(3) at Error
    at jsStackTrace (http://localhost:7000/OggVorbisEncoder.min.js:1:20761)
    at stackTrace (http://localhost:7000/OggVorbisEncoder.min.js:1:20944)
    at abort (http://localhost:7000/OggVorbisEncoder.min.js:13:29426)
    at ue (http://localhost:7000/OggVorbisEncoder.min.js:6:77469)
    at tb (http://localhost:7000/OggVorbisEncoder.min.js:5:9548)
    at Ad (http://localhost:7000/OggVorbisEncoder.min.js:6:40054)
    at Encoder.process (http://localhost:7000/OggVorbisEncoder.min.js:13:30916)
    at Encoder.finish (http://localhost:7000/OggVorbisEncoder.min.js:13:30632)
    at onmessage (http://localhost:7000/worker.js:12:23)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

**Comment by AhmedHashem94** [comment]
similar issue here in 2020
